INSERT INTO libros (categoria_id,titulo,autor_ilustrador,serie,procedencia,cantidad_total,cantidad_disponible,seccion,estado)
VALUES
(1,'Tiny y las alas del corazón','Yemina Mascareño','LUDOS','Compra',1,1,'L',TRUE),
(1,'Wally y el paraíso azul','Yemina Mascareño','LUDOS','Compra',1,1,'L',TRUE),
(1,'Mis fábulas favoritas','David Jiménez','Hemma','Donación',1,1,'L',TRUE),
(1,'Ciclo de la leche','Cristina Quetal, Mariana Magalháes. Sandra Serra.','Everest','Compra',1,1,'L',TRUE),
(1,'Hannah Montana "La novela"','Dan Berendsen','Montena','Donación',1,1,'L',TRUE),
(1,'Félix el príncipe feliz','Yemina Mascareño','LUDOS','Compra',1,1,'L',TRUE),
(1,'Ya duerme en cama','Apple Jordan, John Barret','Great Moments','Compra',1,1,'L',TRUE),
(3,'Cazadores de Bichos','Luis Esteban Villanueva','sm, saber','Compra',1,1,NULL,TRUE),
(1,'Angie & Vitamina','Antonio Mateo Allende','V&R','Donación',1,1,'L',TRUE),
(7,'Mi primer diccionario de flora de México','Pedro Moreno','sm, saber','Compra',1,1,NULL,TRUE),
(1,'Un cuento cada día','Disney Company','Hachette','Compra',1,1,NULL,TRUE),
(1,'Sapo tiene miedo','Max Velthuijs','Ekaré','Compra',1,1,'L',TRUE),
(1,'Rumbo a las Galápagos','Laurie Krebs','sm, saber','Compra',1,1,'L',TRUE),
(3,'¡Qué raro!','Montserrat Ribas','Parragon','Compra',1,1,'I',TRUE),
(1,'Declaración Universal de los Derechos Humanos','Ruth Rocha y Otavio Roth','United Nations','Compra',1,1,'I',TRUE),
(6,'Chico de Buen y los números','Gilles Tibo/Marie-Claude Favreau','sm, saber','Compra',1,1,'L',TRUE),
(4,'El desierto','Edna Torres/ Gerardo Díaz','Conafe','Compra',1,1,'I',TRUE),
(3,'Experimentos Sencillos','Louis V. Loeschnig','Oniro','Compra',1,1,'I',TRUE),
(1,'El delfín curioso','Jesus Araujo','Parramón','Compra',1,1,'L',TRUE),
(6,'Animales','Louis Weber','Ediciones Aguila Real','Compra',1,1,NULL,TRUE),
(1,'Zony un día de emociones','Yemina Mascareño','LUDOS','Compra',1,1,'L',TRUE),
(1,'Ciclo del arroz','Cristina Quetal, Mariana Magalháes. Sandra Serra.','Everest','Compra',1,1,'L',TRUE),
(6,'Descubre las arañas','Alejandro Algarra/ Daniel Howarth','Edebé','Compra',1,1,'I',TRUE),
(1,'El pincel mágico','Francoise Jay/ Zhong Jie','Editorial Juvenil','Compra',1,1,NULL,TRUE),
(6,'Los opuestos','Colección Educa','García','Donación',1,1,'I',TRUE),
(1,'El pingüino Pedro y Pat','Marcus Pfister','Norte-Sur','Compra',1,1,'L',TRUE),
(6,'Atacar y Defender','Josep María Barres Manuel','Parramón','Donación',1,1,'I',TRUE),
(3,'Acertijos para los más pequeños','Yavé Gutiérrez','EMU','Compra',1,1,'I',TRUE),
(1,'Ciclo del pan','Cristina Quetal, Mariana Magalháes. Sandra Serra.','Everest','Compra',1,1,'L',TRUE),
(1,'La tinta de las moras','Georgina Hernández Samaniego','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'La pequeña bruja mide todo','Heung-gyu Kim/ Dong Oh','Astrolabio','SEP',1,1,'L',TRUE),
(3,'Acertijos matemáticos del ogro feroz','Grigory Oster','Astrolabio','SEP',1,1,'I',TRUE),
(1,'Malintzin "La noche de Marina"','María Baranda','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Oro de Indias','Carlos Villanes Cairo','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Breve Antología De Ciencia Ficción','Clarke, Bradbury, Sturgeon,Smith','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Flotante','David Wiesner','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'Baby-sitter blues','Marie-Aude Murail/ Tania Janco','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Peligro en la Aldrea de las letras','María Eugenia Mendoza Arrubarrena','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Wilson, el chiflado','Mark Twain','Astrolabio','SEP',2,2,'L',TRUE),
(6,'200 ideas para pintar y dibujar','Fiona Watt','Astrolabio','SEP',1,1,'I',TRUE),
(3,'Julio Verne','Jordi Cabré/Víctor Escandell','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El amor y la amistad','Oscar Brenifier/Jacques Després','Astrolabio','SEP',1,1,NULL,TRUE),
(6,'Tres veces Miguel Hidalgo','Natalia Ferreiro Reyes Retana/Alejandro Magallanes','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Las piezas del rompecabezas','Rebeca Orozco/Patricia Bergna','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Fibonacci "El soñador de números"','Joseph D''Agnese/ John O''Brien','Astrolabio','SEP',1,1,'L',TRUE),
(6,'Jardín del mar','Coral Bracho /Gerardo Suzan','Astrolabio','SEP',1,1,'L',TRUE),
(6,'Tesoros de Xochimilco','Jaime Beltrán Romero, Ana Luisa Montes de Oca Vega','Astrolabio','SEP',1,1,'L',TRUE),
(3,'La luz y los colores','Carla Baredes e Ileana Lotersztain','Astrolabio','SEP',1,1,'I',TRUE),
(3,'Lo más espeluznante de la medicina','Richard Platt','Astrolabio','SEP',1,1,'I',TRUE),
(1,'25 cuentos populares de miedo','Ana Cristina Herreros y Ramon Besora','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'Un pie en la oreja y el otro en la nariz','Maia F. Miret / David Silva','Astrolabio','SEP',1,1,NULL,TRUE),
(3,'El foco','Jennifer Fandel','Astrolabio','SEP',1,1,'I',TRUE),
(6,'Tengo derecho a un hogar','Jean Harrison','Astrolabio','SEP',1,1,'I',TRUE),
(6,'México diverso y plural Cultura y lenguas.','Jaime Labastida/ Felipe de la Torre','Astrolabio','SEP',1,1,'I',TRUE),
(1,'La historia de la abuela','Carlos Pellicer López','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Cicatrices','Marcelo Birmajer','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Don quijote de la Mancha','Miguel de Cervantes Saavedra /Felipe Garrido','Astrolabio','SEP',1,1,'L',TRUE),
(1,'La canción del grillo','Cristina Pacheco/ Maia Miller','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El mismo que viste y calza','Catalina Kühne Peimbert/Tepatlaxco','Astrolabio','SEP',1,1,'L',TRUE),
(3,'Cómo y por qué','Alberto Fuentes','Astrolabio','SEP',1,1,'I',TRUE),
(1,'La decena trágica','José Manuel Villalpando','Astrolabio','SEP',1,1,'L',TRUE),
(6,'Libros','Charlotte Stowell','Astrolabio','SEP',1,1,'I',TRUE),
(1,'¿Comida basura? No, gracias','Kate Knighton y aAdam Larkum','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'¡Ay! ¡Me pica!','Brigitte Marleau','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Cuentos de microbios','Arthur Kornberg','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Piratas','Thierry Aprile','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El Gran libro del misterio','Antonio Tello/ Miguel Navia','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Moby Dick','Jean Rouaud/Denis Deprez','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'Mis amigos de El colegio Nacional','Lesli Alger/Ruy Pérez Tamayo','Astrolabio','SEP',1,1,'I',TRUE),
(1,'Kipatla:Cuentos para tratarnos igual','Nuria Gómez Benet','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El señor todo azul','Monika Feth','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El gran libro de leyendas medievales','Francese Miralles/Aoria Frutos','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Ojos con alas','Moy Volcovich','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Cuentos para una noche de insomnio','Jorge A. Estrada','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Leyendas de Bécquer contado a los niños','Rosa Navarro Durán/ Francesc Rovira','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Doctora Judy Moody','Megan McDonald','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Amigos del alma','Elvira Lindo','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Del tamaño justo','Ana Maria Machado','Astrolabio','SEP',1,1,'L',TRUE),
(1,'La tortuga gigante','Horacio Quiroga/Sandra La potra','Astrolabio','SEP',1,1,'L',TRUE),
(1,'¡Judy Moody se vuelve Famosa!','Megan McDonald','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El devorador de hombres','Horacio Quiroga','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Cuentos del Japón','Maria Manent/Luis Filella','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Estaba oscuro y sospechosamente trabquilo','Einar Turkowski','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'La tinta de las moras','Georgina Hernández Samaniego','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Cartas a Bárbara','Leo Meter','Astrolabio','SEP',1,1,'L',TRUE),
(1,'Los doce trabajos de Hércules','James Riordan','Astrolabio','SEP',1,1,'L',TRUE),
(1,'El libro de las fábulas','Emilio Urberuaga','Astrolabio','SEP',1,1,'L',TRUE),
(1,'¿Por qué te pareces a mamá y a papá?','Myung-gil Lee/Ye-jung Cho','Astrolabio','SEP',1,1,'I',TRUE),
(1,'Lian','Chen Jiang Hong','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'Cervantes: Un escritor en busca de la libertad','Eduardo Murias de Aller/antonio Rey Hazas','Astrolabio','SEP',2,2,'L',TRUE),
(6,'Nuestro mundo es agua','Bestrice Hollyer','Astrolabio','SEP',1,1,NULL,TRUE),
(6,'El regalo de los mayas','Silvia Dubovoy/Marta Rivera','Astrolabio','SEP',1,1,'I',TRUE),
(6,'Bandera de México','Miguel Ángel Porrúa','Astrolabio','SEP',1,1,'I',TRUE),
(4,'La Ecología','Charline Zeitoun/Peter allen','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Qué han cambiado los inventos','Melvil Dewey','Astrolabio','SEP',1,1,'I',TRUE),
(4,'La historia de los inventos','Anna Claybourne y Adam Larkum','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Fiestas, fandango, música y alegría en México','Melvil Dewey','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Números para contar, medir,crear y soñar','José Antonio De la Peña','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Sólo. un segundo: Una manera distinta de percibir el tiempo','Steve Jenkins','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Mi pequeña antología del ARTE','Rosie Dickins','Astrolabio','SEP',1,1,NULL,TRUE),
(4,'Matemáticas asombrosas de matemáticos excentricos','Seokku Ko/Jin-wha Kim','Astrolabio','SEP',1,1,'I',TRUE),
(4,'El calientamiento Global','Cercilia Conde y Rosa María Ferrer','Astrolabio','SEP',1,1,'I',TRUE),
(4,'El cuerpo','Stephanie Turnbull y Adam Larkum','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Con los ojos cerrados: Sueños de los niños indígenas','Gabriela Olmos','Astrolabio','SEP',1,1,'L',TRUE),
(4,'Un atlas en imágenes del mundo','Melvil Dewey','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Usos de la basura','Ester Matiana García Amador y Leticia López Vicente','Astrolabio','SEP',1,1,NULL,TRUE),
(4,'Cien cosas que debes saber sobre la ciencia','Melvil Dewey','Astrolabio','SEP',1,1,'I',TRUE),
(4,'¡Un increíble espectáculo! El sol, la Tierra y la Luna','Laura Patricia Cabellero Leal/ Hilda M.Cabellero Leal','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Tu calorías y las calorías','Marta Badino/Gabriela Muñoz','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Peligro animales en extinción','David Burnie','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Las máquinas simples que nos simplifican la vida','Héctor ángel Domínguez Álvarez','Astrolabio','SEP',1,1,'I',TRUE),
(4,'Nuestro mundo es agua','Bestrice Hollyer','Astrolabio','SEP',1,1,NULL,TRUE),
(1,'El principito','Antoine de Saint-Exupéry','Clásicos del mundo','Donación',2,2,'L',TRUE),
(1,'Nuestra amistad es para siempre','Kim Anderson','V&R','Compra',1,1,'L',TRUE),
(1,'Mancha, el diablillo de los errores','Cornelia Ziegler','ESAF','Compra',1,1,'L',TRUE),
(1,'La isla del tesoro','Robert L. Stevenson','grijalbo','Compra',1,1,'L',TRUE),
(1,'Daniel aprende a organizarse','Pick, Vargas.Rubio','Noriega Editores','Compra',1,1,'L',TRUE),
(4,'Vermicultura y Huertos familiares','Dra. María Cristina Castañón','Vermicultura UABC','Donación',1,1,'I',TRUE),
(1,'El Lazarillo de Tormes','Margarita Avila Aldrete','Novis Omnibus','Donación',1,1,'L',TRUE),
(1,'Miguel de Cervantes','Edna Iturralde','Alfaguara','Compra',1,1,'L',TRUE),
(1,'Juan y los frijoles mágicos','Richard Walker','Barefoot','Compra',1,1,'L',TRUE),
(1,'¡La señorita Nelson ha desaparecido!','Harry Allard','Sandpiper','Compra',1,1,'L',TRUE),
(1,'Adivina cuanto te quiero','Sam McBratney','KóKINOS','Compra',1,1,'L',TRUE),
(1,'Susy y Arquímedes','Eva Furnari','Punto de encuentro','Compra',3,3,'L',TRUE),
(1,'El sastrecillo valiente','Zoraida Vásquez','trillas','Compra',1,1,'L',TRUE),
(1,'Hércules y la Chispa','Margarita Hever','Trillas','Compra',1,1,'L',TRUE),
(6,'500 acertijos','Yavé Gutiérrez','EMU','Compra',1,1,'L',TRUE),
(6,'Los cinco sentidos','Annette Tison','Libro del rincon','Compra',1,1,'I',TRUE),
(6,'Arte e Historia Egipto','Alberto Carlo','Bonechi','Compra',1,1,'I',TRUE),
(6,'Grandes descubrimientos','Claire LLewellyn','SM, saber','Compra',1,1,'I',TRUE),
(5,'Zazan Tleino','José Antonio Flores','Artes de México','Compra',1,1,'L',TRUE),
(1,'Si la Tierra está enferma ¡Yo también!','Hanulddang/ Jeong-seok Baik','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'¿Por qué no?','Heráclito López /Mora Diez','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Carlota y Monna Lisa','James Mayhew','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'¿Quién se comió el queso?','Kim Sook Kyeong /Jang Jung Oh','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Una vaca en el tejado','Eric maddern/Paul Hess','Pasos de luna','SEP',1,1,'L',TRUE),
(6,'A B C de las artesanías','Ma. Cristina Urrutia','Pasos de luna','SEP',1,1,'L',TRUE),
(3,'Un libro en tamaño real','Jorge Doneiger','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'El iglú','Alan Mets','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Cara de chapulín','Anna Witte/Vanessa Brown','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'La verdadera historia de los colores para niños amantes de la pintura','Eva Heller','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'Gira y gira','Young-jik Kwag / Iris Wolfermann','Pasos de luna','SEP',1,1,NULL,TRUE),
(4,'El gran poder de la naturaleza','Yun-hui Hong / Sun-ho Kim','Pasos de luna','SEP',1,1,NULL,TRUE),
(6,'Entre todos es más fácil','Virginia Ferrari / Matías Bervejillo','Pasos de luna','SEP',1,1,'L',TRUE),
(5,'Calavera de calacas','Eduardo Bustos','Pasos de luna','SEP',1,1,'L',TRUE),
(6,'Ni tanto','Menena Cottin','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Biblioburro','Jeanette Winter','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'Cuando nos hayamos comido el planeta','Alain Serres/Silvia Bonanni','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Los tesoros del bosque','Pere Martí i Bertran/Anna Mongay','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'D de despedida','Ifeoma Onyefulu','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'¡A que no me la adivinas!','Avilio González/Coralia López','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'Reducir, Reutilizar y Reciclar','Anna Nolla, Susanna Aránega','Pasos de luna','SEP',1,1,NULL,TRUE),
(6,'¿Conoces las partes de tu cuerpo?','Núria Roca','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'Un cascabel para el terrible gato','Choi Yun- Jeong','Pasos de luna','SEP',1,1,'L',TRUE),
(6,'Adivina en qué pais','Martina Badstuber','Pasos de luna','SEP',1,1,NULL,TRUE),
(6,'Ronda de juegos','Vivian Mansour Manzur','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'La otra orilla','Marta Carrasco','Pasos de luna','SEP',1,1,'L',TRUE),
(5,'Trabamáslenguas','David Chericán','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'El aire','Philippe Nessmann','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'y ¿Por qué?','Claudia Bielinsky','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'El lobo culto','Becky Bloom','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'¿Por qué la noche es oscura?','José Manuel Mateo','Pasos de luna','SEP',1,1,NULL,TRUE),
(6,'Animales sorprendentes del mundo','Peter David Scott','Pasos de luna','SEP',1,1,NULL,TRUE),
(5,'Sentir humor','Alma Velasco/Ericka Martínez','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'200 amigos para 1 sola vaca','Alessia Garilli/Miguel Tanco','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Nozi Madrina de libros','Gcina Mhlophe/ Lyn Gilbert','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'El último día de verano','Cristina Pérez Navarro','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Relatos de Billabong','James Vance Marshall','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'El viaje del bisabuelo','Marta Farias/Aitana Carrasco','Pasos de luna','SEP',1,1,'L',TRUE),
(4,'La Tierra y el espacio','Anita Ganeri','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'La cebra Camila','Marisa Núñez/Óscar Villán','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Los cuatro amigos','Sara Navas','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'El anillo de las matemáticas','Sylvie de Mathuisieulx','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Soy sorda','Jennifer Moore- Mallinos','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Cuando sea mayor quiero ser Premio Nobel de la Paz','Isabel Pin','Pasos de luna','SEP',1,1,'L',TRUE),
(6,'¡Qué buen cálculo!','Bruce Goldstone','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'Un día diferente para el señor Amos','Philip C. Stead','Pasos de luna','SEP',1,1,'L',TRUE),
(5,'Adivina, Adivinanza','Elva Macías/ Felipe Ugalde','Pasos de luna','SEP',1,1,'L',TRUE),
(6,'Como leer un códice','Esther Jacob','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'La voz de los sueños y otros cuentos prodigiosos','Hugh Lupton','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'El campeón de los niños','Tomek Bogacki','Pasos de luna','SEP',1,1,'L',TRUE),
(3,'Experimentos sencillos con fuerzas y ondas','Hans jurgen Press','Espejo de urania','SEP',1,1,NULL,TRUE),
(1,'La Piedra Azul','Jimmy Liao','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'La Máquina del tiempo','Alejandro Spiegel/ Segio Saposnic','Espejo de urania','SEP',1,1,'L',TRUE),
(6,'Atlas cósmico','José de la Herrán','Espejo de urania','SEP',1,1,NULL,TRUE),
(1,'Guillermo González Camarena : Habitantes del futuro','Jaime Muñoz Vargas, Jorge Aldrete','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Tu´u ñuu savi/ Relatos mixtecos','Alejandra Cruz Ortiz','Espejo de urania','SEP',1,1,'L',TRUE),
(3,'Imagen y sonido','Alicia Rodriguez','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Los miserables','Victor Hugo','Espejo de urania','SEP',2,2,'L',TRUE),
(1,'La vida y la muerte','Brigitte Labbé/ Michel Puech','Espejo de urania','SEP',1,1,'L',TRUE),
(3,'Adicción a nuevas tecnologías','Elisardo Becoña Iglesis','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'La Revolución imaginada','Alfredo Vilchis','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Imágenes de Francisco Villa','Friedrich Katz','Espejo de urania','SEP',1,1,'I',TRUE),
(6,'Matemáticas','Wolfgang Blum/Joachim Knappe','Espejo de urania','SEP',2,2,NULL,TRUE),
(1,'La Independencia de México','José Manuel Villalpando/ JKulián Cicero','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Una visión, un sueño','Santos Motoaopohua de la Torre de Santiago','Espejo de urania','SEP',2,2,'L',TRUE),
(1,'Del cacao al dólar','Arturoo Curiel Ballesteros/Felipe Dávalos','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'b de Bicentenario','Julio Derbez','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Scott y Amundsen: La conquista del Polo Sur','K.T.Hao/Montserrat Fulla','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'México a tráves de su narrativa','Greco Sotelo','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Teotihuacan: Una para toda Mesoaméricana','Vit Suzán,Ilan','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Piratas y traficantes','Moira Butterfield','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Respeto a la igualdad','Rita Radl Philipp','Espejo de urania','SEP',1,1,'I',TRUE),
(3,'¡Beee!','Cynthia Pratt Nicolson','Espejo de urania','SEP',1,1,'I',TRUE),
(3,'Mantente saludable: un plan personal','Laura Vargas Parada','Espejo de urania','SEP',1,1,'I',TRUE),
(3,'Cómo conservar sus dientes y encías toda la vida: odontología para pacientes','Agustín Zerón','Espejo de urania','SEP',1,1,'I',TRUE),
(4,'El desarrollo sostenible a tu alcance','Catherine Stern/Pénélope Paicheler','Espejo de urania','SEP',1,1,'I',TRUE),
(3,'Historia de los inventos ¿Cómo? ¿Cuándo? ¿Por que?','Louise Spilsbury','Espejo de urania','SEP',1,1,'I',TRUE),
(3,'e.explora Tierra','Matt Turner','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Miradas entrevistas','Sarah Corana Berkin','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Romeo & Juliet','Adam McKeown','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Cuentos de aprendizaje','Heker- Dal Masetto- Moyano - Ocampo- Castillo- De Miguel- Birmajer- Cortázar','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Elemental,Watson','Arthur conan Doyle','Espejo de urania','SEP',2,2,'L',TRUE),
(1,'Bajo espino: Los niños de la hambruna','Marita Conlon-Mckenna /Ricardo Peláez','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'El Tiempo repentino: Crónicas de la Ciudad de México en el siglo XX','Héctor de Mauleón','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Ajuar funerario','Fernando Iwasaki','Espejo de urania','SEP',2,2,'L',TRUE),
(1,'El signo del gato','Ray Bradbury','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Mentiras y exageraciones una antología','Elisa Ramírez Castañeda','Espejo de urania','SEP',2,2,'L',TRUE),
(1,'Relatos mexicanos posmodernos','Lauro Zavala','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Léperas contra mocosos','Francisco Hinojosa','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'cuentos que cuentan los indios','Gustavo Roldán/Luis Scafati','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Oda a una estrella','Pablo Neruda/Elena Odriozola','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Cacaxtla macuilitzin, La historia de un tlacuilo','Luisa Maínou VCervantes/ Ricardo Castro Mendoza','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Cuentos a seis manos','Angélica González Macías/Artemio Ríos Rivera/ Martha Elena Nava Tablada','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Las pasiones de Émilie','Élisabeth Badinter/ Jacqueline Duheme','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Escribir América: Crónicas de viajes por América Latina','Federico Guzmán','Espejo de urania','SEP',1,1,'L',TRUE),
(3,'La manzana de Einstein','Francisco Noreña Villarías','Espejo de urania','SEP',1,1,'L',TRUE),
(3,'Moléculas en una Exposición','John Emsley','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'El soldado y la niña','Jordi Sierra','Pasos de la luna','SEP',1,1,'L',TRUE),
(1,'Un oscuro resplandor','Dr. Patch','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'El mosquito, zumbador','Verónica Uribe',NULL,'Donación',1,1,'L',TRUE),
(6,'La casa y el hogar.','Alastair Smith','Pasos de luna','SEP',1,1,'L',TRUE),
(3,'Los primeros descubrimientos','Gerry Bailey','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'Frida','Jonah Winter','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'El fantasma de la ópera','Gastón Leroux','Espejo de urania','SEP',1,1,'L',TRUE),
(4,'Planeta Tierra','Sergio Almazán Esqueda','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Relatos escalofriantes','Roal Dahl','Espejo de urania','SEP',1,1,'L',TRUE),
(4,'El reciclaje a tu alcance','Gérard Bertolini y Claire Delalande','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Los diez magníficos','Anna Cerasoli','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Así cuentan los mayores','Clemente Cruz Huahuichi','Espejo de urania','SEP',1,1,NULL,TRUE),
(6,'Conocer para conservar (animales mexicanos en peligro)','Alejandra Alvarado Zink','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Fernando Botero la pasión de crear','César Vidal','Espejo de urania','SEP',1,1,'L',TRUE),
(6,'Atlas cósmico','José de la Herrán','Espejo de urania','SEP',1,1,NULL,TRUE),
(1,'Los últimos gigantes','Francois Place','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Mitos Griegos','Nathaniel Hawthorne','Espejo de urania','SEP',1,1,'L',TRUE),
(5,'Ellas voces poemas','Ana Belén López','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'La revolución mexicana','Susana Sosenski','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Robinson Crusoe','Daniel Defoe','Espejo de urania','SEP',1,1,'L',TRUE),
(6,'Diccionario de sinónimos, ideas afines, antónimos y parónimos','Melvil Dewey','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'Un hombre con un tenedor en una tierra de sopas.','Jordi Sierra','Espejo de urania','SEP',1,1,NULL,TRUE),
(1,'Ecos del desierto','Silvia Dubovoy','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'aquí están los que se van','Gabriel Quiroz','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'Molly Moon y el increíble libro del hipnotismo','Georgia Byng','sm','compra',1,1,'L',TRUE),
(1,'Molly Moon viaja a través del tiempo','Georgia Byng','sm','compra',1,1,'L',TRUE),
(1,'Molly Moon detiene el mundo','Georgia Byng','sm','compra',1,1,'L',TRUE),
(1,'Harry Potter y la piedra filosofal','J.K Rowling','salamandra','compra',2,2,'L',TRUE),
(1,'Harry Potter y la cámara secreta','J.K Rowling','salamandra','compra',1,1,'L',TRUE),
(1,'Ilíada','Homero','Espejo de urania','SEP',1,1,NULL,TRUE),
(1,'chico de buen y la música','Gilles Tibo','sm','compra',1,1,NULL,TRUE),
(3,'La genética','Christian Léourier','sm','compra',1,1,'I',TRUE),
(1,'Ciclo del chocolate','Cristina Quental/Mariana Magalhnáes','everest','compra',1,1,'L',TRUE),
(1,'El burrito y la Tuna','Ramón Ipuana Paz','al sol solito','SEP',1,1,'L',TRUE),
(6,'Adivina quién es','Joaquín Gasca','al sol solito','SEP',1,1,'I',TRUE),
(1,'El sueño de dos amigos','Shin Ji- Yun/ Lee Hyeon-Jeong','al sol solito','SEP',1,1,'L',TRUE),
(1,'El niño y la ballena','Marcela Recabarren','al sol solito','SEP',1,1,'L',TRUE),
(1,'Croniñón','Michel Gay','al sol solito','SEP',1,1,NULL,TRUE),
(6,'Las señales del cuerpo','Hong Yun-Jeong/ Kim Ji-Ah','al sol solito','SEP',1,1,'L',TRUE),
(1,'Juguemos a contar','Elisabet Ballart','al sol solito','SEP',2,2,'L',TRUE),
(1,'Crisantemo','Kevin Henkes','al sol solito','SEP',1,1,NULL,TRUE),
(1,'Ruidos bajo la cama','Mathis','al sol solito','SEP',1,1,'L',TRUE),
(6,'Palabras para conocer el mundo','Julieta Fierro','al sol solito','SEP',1,1,'L',TRUE),
(6,'¿Juegas conmigo?','Janice Lobb','al sol solito','SEP',1,1,'I',TRUE),
(1,'Un puñado de besos','Antonia Rodenas','al sol solito','SEP',2,2,'L',TRUE),
(1,'La gota de agua','Triunfo Arciniegas','al sol solito','SEP',1,1,NULL,TRUE),
(1,'No estás','Carmen Leonor Rivera-Lassén','al sol solito','SEP',1,1,'L',TRUE),
(1,'Johanna en el tren','Kathrin Schärer','al sol solito','SEP',1,1,'L',TRUE),
(6,'Viaje a través de tu cuerpo','Laura Patricia Caballero Leal','al sol solito','SEP',1,1,'I',TRUE),
(1,'Matías y el pastel de fresas','José Palomo','al sol solito','SEP',1,1,'L',TRUE),
(1,'Mi isla herida','Jacques Pasquet','al sol solito','SEP',1,1,'L',TRUE),
(1,'Mis manos','Aliki','al sol solito','SEP',1,1,'L',TRUE),
(1,'A comer','Ana Zamorano','al sol solito','SEP',1,1,'L',TRUE),
(1,'Bailando con degas','Julie Merberg','al sol solito','SEP',1,1,'L',TRUE),
(1,'Amo las bibliotecas','Iris Borges','al sol solito','SEP',1,1,NULL,TRUE),
(6,'Por qué suena el teléfono','Richard Mead','al sol solito','SEP',1,1,'I',TRUE),
(1,'La abuelita de arriba y la abuelita de abajo','Tomie dePaola','al sol solito','SEP',1,1,'L',TRUE),
(1,'La revancha de los conejos','Suzy Lee','al sol solito','SEP',1,1,NULL,TRUE),
(1,'El Tigre y el Rayo','Fray Cesáreo de Armellada','al sol solito','SEP',1,1,'L',TRUE),
(1,'El secreto de los libros','Roger Paré','al sol solito','SEP',1,1,NULL,TRUE),
(1,'¡Qué rico banquete!','Lynette Evans','al sol solito','SEP',1,1,'L',TRUE),
(6,'Día y noche en los bosques','Susan y Peter Barrett','Colección Hábiats','compra',1,1,NULL,TRUE),
(6,'Los exploradores de National Geographic Tiburones','Taylor Leighton','Weldon Owen','compra',1,1,NULL,TRUE),
(6,'Terremotos y Volcanes','Lin Sutherland','Weldon Owen','compra',1,1,NULL,TRUE),
(6,'Dinosaurios','Paul Willis','Weldon Owen','compra',1,1,NULL,TRUE),
(6,'Insectos y arañas','Matthew Robertson','Weldon Owen','compra',1,1,NULL,TRUE),
(6,'En el arrecife de coral','Caroline Bingham','sm','compra',1,1,'I',TRUE),
(1,'Harry Potter y la orden del Fénix','J.K Rowling','salamandra','compra',1,1,'L',TRUE),
(6,'Nosotros los animales','Andrea Mills','sm','compra',1,1,'I',TRUE),
(6,'Criaturas emplumadas','Clint Twist','sm','compra',1,1,'I',TRUE),
(1,'Juárez con la República bajo el brazo','Claudia Burr','Ediciones Tecolote','compra',1,1,NULL,TRUE),
(5,'De todo corazón','Salvador Novo, Rubén Bonifaz','astrolabio','SEP',1,1,'L',TRUE),
(1,'¿Qué tanto sabes sobre el circo?','Gabriel Olmos','Pasos de luna','SEP',1,1,'L',TRUE),
(1,'Mamá no me contó','Babette Cole','Pasos de luna','SEP',1,1,NULL,TRUE),
(1,'El maestro de la Lira','Orfeo','Pasos de luna','SEP',1,1,NULL,TRUE),
(6,'¿Qué sabes de los delfines?','Harley Chan','al sol solito','SEP',1,1,'I',TRUE),
(1,'Ocho Venado, garra de jaguar','Krystyna M. Libura','astrolabio','SEP',1,1,'I',TRUE),
(6,'Historias de plantas en el Valle de México','Ana Luisa Montes de Oca','Espejo de urania','SEP',1,1,'I',TRUE),
(1,'¿Puede volar un cangrejo?','Florencia Esses y Graciela Repún','Pasos de luna','SEP',1,1,'L',TRUE),
(6,'Manejo de la basura','Luis Lesur','Trillas','Donación',1,1,NULL,TRUE),
(1,'Rin-Rin Renacuajo','Rafael Pombo','SEP','SEP',1,1,'L',TRUE),
(1,'El abuelo ya no duerme en el armario','Silvia Molina','Corunda','SEP',1,1,'L',TRUE),
(1,'El enmascarado de lata','Vivian Mansour Manzur','CFE','compra',1,1,'L',TRUE),
(6,'Arrecifes artificiales','Manuel Sarmiento','México desconocido','SEP',2,2,'I',TRUE),
(6,'El cuerpo humano','Laurie Beckelman','Weldon Owen','compra',1,1,NULL,TRUE),
(1,'Sara la cirquera','Gudrun Mebs','Castillo','compra',1,1,'L',TRUE),
(1,'Un caso  grave de rayas','David Shannon','Scholastic','compra',1,1,'L',TRUE),
(1,'Valeria Varita Hadas de Hoy','Emma Thomson','Beascoa','compra',1,1,'L',TRUE),
(1,'El libro apestoso','Babette cole','FCE','compra',1,1,NULL,TRUE),
(1,'Vida de peros','Isol','FCE','compra',1,1,'L',TRUE),
(1,'¿Para qué sirve un niño?','Colas Gutman','FCE','compra',1,1,'L',TRUE),
(1,'La abuelita tejedora','Uri Orlew','FCE','compro',1,1,'L',TRUE),
(1,'Las golosinas secretas','Juan Villoro','FCE','compra',1,1,'L',TRUE),
(1,'Ricardo','Helme Heine','FCE','compra',1,1,NULL,TRUE),
(1,'Los días raros','Roger Ycaza/María Fernanda Heredia','FCE','compra',1,1,'L',TRUE),
(1,'Vitamina, ¿dónde estás?','Carla Baredes e Ileana Lotersztain','Nuevo modelo educativo','SEP',1,1,NULL,TRUE),
(1,'¡Mi maestra es un Monstruo!','Peter Brown','Nuevo modelo educativo','SEP',1,1,NULL,TRUE),
(1,'Asquerosología en acción','Sylvia Branzei/Jack Keely','Nuevo modelo educativo','SEP',1,1,'I',TRUE),
(1,'Una casa de 100 pisos','Toshio Iwai','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Cierra los ojos','Victor Pérez Escrivá/ Claudia Ranucci','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'¿Qué prefieres... cenar con un escarabajo o almorzar con un bicho?','Camilla de la Bédoyére/Mel Howells','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Mi primer libro de príncipes y princesas','Grimm,Jakob','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'La mejor familia del  mundo','susana López/Ulises Wensell','SM','compra',1,1,NULL,TRUE),
(1,'Ríbit','Juan Gedovius','SM','compra',1,1,'L',TRUE),
(1,'De camino a la escuela','Anne Bouin','SM','compra',1,1,'L',TRUE),
(6,'En la charca: Día y noche en la vida de los animales de la charca','Water bole','SM','compra',1,1,NULL,TRUE),
(1,'Chico de buen y las imagenes','Gilles Tibo','SM','compra',1,1,'l',TRUE),
(1,'Ardilla Miedosa','Mélanie Watt','SM','compra',1,1,NULL,TRUE),
(1,'Un elefante sin circo','Alejandro Sandoval Ávila','SM','compra',1,1,'L',TRUE),
(1,'Dino Huellas','Bob Barner','SM','compra',1,1,NULL,TRUE),
(1,'Pequeña Mancha','Lionel Le Néouanic','Castillo','Compra',1,1,'L',TRUE),
(3,'Internet ¿Cómo ha cambiado al mundo?','Hyang-suk Choi','Castillo','Compra',1,1,NULL,TRUE),
(6,'¿A qué huelen las guayabas?','Eva Salgado','Sep','SEP',1,1,'L',TRUE),
(1,'El caballito jorabado','Yerchoff','Sep','SEP',2,2,'L',TRUE),
(1,'Historias para leer y oír','Francisco Hernández','Sep','SEP',2,2,'L',TRUE),
(1,'La brujita atarantada','Eva Furnari','Sep','SEP',2,2,'L',TRUE),
(1,'De los huevecillos a la rana','Marlene Reidel','Sep','SEP',1,1,'I',TRUE),
(1,'El problema de Odi','Eva Furnari','Sep','SEP',1,1,'L',TRUE),
(1,'Antología primer grado','Laura Nakamura','Sep','SEP',3,3,'L',TRUE),
(6,'Diccionario Sinónimos y antónimos','Miguel Subercaseaux','Programa Educativo Visual','Compra',1,1,NULL,TRUE),
(3,'Experimentos con agua','Bryan Murphy','Scholastic','Compra',7,7,'I',TRUE),
(3,'El autobus magico viaja por el agua','Joanna Cole y Bruce Degen','Scholastic','Compra',1,1,'L',TRUE),
(3,'La razon de ser de una flor','Ruth Heller','Scholastic','Compra',1,1,NULL,TRUE),
(3,'Whats under the ocean','Melvin and Gilda Berger','Scholastic','Compra',1,1,'I',TRUE),
(2,'Veo - Un libro de adivinanzas Ilustradas','Jean Marzollo','Scholastic','Donación',2,2,'L',TRUE),
(2,'De colores y cosas','Tana Hoban','Scholastic','Compra',1,1,'I',TRUE),
(2,'Escalofrios La noche del muñeco viviente II','R. L. Stine','Scholastic','compra',1,1,'L',TRUE),
(2,'¿Como se curan los dinosaurios?','Jane Yolen y Mark Teague','Scholastic','Compra',1,1,'L',TRUE),
(6,'Nuestro Mundo  Vol. 2','Solares - Textos','Scholastic','Compra',1,1,NULL,TRUE),
(5,'Bichos de África','Rogério Andrade','SEP','SEP',2,2,'L',TRUE),
(6,'Gente, lugares y cosas','Enciclopedia Británica','Ediciones Aguila Real','Compra',1,1,'I',TRUE),
(6,'Los transportes','Enciclopedia Británica','Ediciones Aguila Real','Compra',1,1,'I',TRUE),
(2,'El Principito','Antoine de Saint- Exupéry','IBALPE','Donación',1,1,'L',TRUE),
(2,'Los conejitos descubren el cielo','Annie López','Hemma','Compra',1,1,'L',TRUE),
(2,'Aníbal y Melquiades','Francisco Hinojosa','CFE','Compra',1,1,'L',TRUE),
(6,'Al son de la letra','Germán Montalvo','Sm','Compra',1,1,NULL,TRUE),
(2,'Cenicienta',NULL,'Grupo editorial','Compra',1,1,'L',TRUE),
(2,'Conquistador del cielo','José Montelongo','sm','compra',1,1,NULL,TRUE),
(2,'Perico y Leopoldo','Ziraldo','Melbooks','Compra',1,1,'L',TRUE),
(6,'Máquinas y herramientas','Disney Ilustrada','Pasa 2007','Donación',2,2,NULL,TRUE),
(6,'Aves Insectos y Arañas','Disney Ilustrada','Pasa 2007','Donación',2,2,NULL,TRUE),
(6,'Comunicaciones/ Transportes','Disney Ilustrada','Pasa 2007','Donación',2,2,NULL,TRUE),
(6,'Atlas del mundo','Disney Ilustrada','Pasa 2007','Donación',1,1,NULL,TRUE),
(6,'Animales Marinos','Disney Ilustrada','Pasa 2007','Donación',1,1,NULL,TRUE),
(6,'Dinosaurios','Disney Ilustrada','Pasa 2007','Donación',1,1,NULL,TRUE),
(6,'Teatro,, música y danza. Pintura y escultura','Disney Ilustrada','Pasa 2007','Donación',2,2,NULL,TRUE),
(6,'Momentos de la Historia/ Viajeros Exploradores','Disney Ilustrada','Pasa 2007','Donación',1,1,NULL,TRUE),
(6,'El Planeta Tierra/ La vida de las plantas','Disney Ilustrada','Pasa 2007','Donación',1,1,NULL,TRUE),
(6,'Deportes /Cuerpo Humano','Disney Ilustrada','Pasa 2007','Donación',2,2,NULL,TRUE),
(6,'Niños del Mundo Grandes biografías','Disney Ilustrada','Pasa 2007','Donación',1,1,NULL,TRUE),
(6,'Gente y lugares','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Cruzando el Espacio','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Vestidos de Pies a Cabeza','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'¿Cómo funcionan las máquinas?','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Criaturas de la Tierra y el Mar','Montserrat Vives','Junior','Donación',2,2,NULL,TRUE),
(6,'Electricidad y Magnetismo','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Nuestro increíble Universo','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Barcos y demás cosas que flotan','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'La ciencia puede ser divertida','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Los animales a través de las épocas','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Aviones y demás cosas que vuelan','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Guía del Planeta Tierra','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'La magia de México','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(6,'Coches, trenes y otros vehículos','Montserrat Vives','Junior','Donación',1,1,NULL,TRUE),
(1,'Aliados de la naturaleza','Hubert Ben Kemoun','sm','Compra',1,1,'L',TRUE),
(1,'Tarde de invierno','Jorge Luján','sm','Compra',1,1,'L',TRUE),
(1,'El paseo de Gustavo','Antonin Louchard','sm','Compra',1,1,'L',TRUE),
(1,'Don Quijote de la Mancha','Carlos Reviejo','sm','Compra',1,1,NULL,TRUE),
(1,'Platero y Juan Ramón','Carlos Reviejo','sm','Compra',1,1,NULL,TRUE),
(1,'Cosas de brujas','Soledad Candel','sm','Compra',1,1,'L',TRUE),
(1,'Xavier X','Mónica González Dillon','sm','Compra',1,1,'L',TRUE),
(1,'El pintor de recuerdos','José Antonio del Cañizo','sm','Compra',1,1,NULL,TRUE),
(1,'Ser y Parecer','Jorge Luján','sm','Compra',1,1,'L',TRUE),
(6,'Los descubrimientos del hombre','Sylvie Baussier','sm','Compra',1,1,'L',TRUE),
(1,'Un barón olímpico','Mónica Nepote','sm','Compra',1,1,'L',TRUE),
(1,'Vaca Blanca','Ana Paula Rosales','sm','Compra',1,1,'L',TRUE),
(5,'Papalote, papelito','Carmen Villoro','sm','Compra',1,1,'L',TRUE),
(1,'Nuestras historias también cuentan','Pequeños escritores','Time Life','Donación',3,3,'I',TRUE),
(3,'Ciencia para niños','varios','Fernandez editores','Compra',1,1,'I',TRUE),
(3,'Naturaleza para niños','varios','Fernandez editores','Compra',1,1,'I',TRUE),
(3,'Matemáticas para niños','varios','Fernandez editores','Compra',1,1,'I',TRUE),
(6,'Países para niños','varios','Fernandez editores','Compra',1,1,'I',TRUE),
(6,'Personajes para niños','varios','Fernandez editores','Compra',1,1,'I',TRUE),
(2,'Escuela de cazadragones','K.H McMullan','Montema','compra',1,1,'L',TRUE),
(2,'Pocahontas','Disney','Fernández','compra',1,1,'L',TRUE),
(2,'La bella durmiente',NULL,'Hemma','compra',1,1,'L',TRUE),
(6,'El taller de Metal','Pernelle Sévy y Serge KomaÏgorodsky','Mas-Ivars','Donación',1,1,'I',TRUE),
(6,'Tú y el medio ambiente','Guillermo solano Flores','NORI','donación',1,1,'I',TRUE),
(2,'La cama de mamá','Joi Freed- Garrod/Morella Fuenmayor','Ekaré','donación',1,1,'L',TRUE),
(2,'La bella y la Bestia','Disney','mediasatgroup','donación',1,1,'L',TRUE),
(2,'Blanca Nieves','Disney','mediasatgroup','donación',1,1,'L',TRUE),
(2,'Antón Pirulero','Alma Flor Ada','Puertas al sol','Donación',1,1,'L',TRUE),
(2,'Ciclo del huevo','Cristina Quental/ Mariana Magalhaes','everest','compra',1,1,'L',TRUE),
(2,'Dinosaurios','Steve Holmes','Silver dolphin','Donación',1,1,'I',TRUE),
(2,'Mitología fantástica para niños','Luis Rutiaga','RTM','Donación',1,1,'L',TRUE),
(2,'Monsters,inc','Disney','Grolier','donación',1,1,'L',TRUE),
(5,'De la a la z por un poeta','Fernando del paso','Libros del rincón','SEP',2,2,'L',TRUE),
(6,'Juegos y manualidades','Tere Valenzuela','EMU','donación',1,1,'L',TRUE),
(2,'Orejas de mariposa','Luisa Aguilar','Kalandraka','compra',1,1,'L',TRUE),
(2,'Ciclo del aceite','Cristina Quental/ Mariana Magalhaes','everest','compra',1,1,'L',TRUE),
(6,'Aves','Edward S. Brinkley','EGEDSA','donación',1,1,NULL,TRUE),
(2,'SOS televisión','Germano Zullo/Albertine','Ekaré','compra',1,1,NULL,TRUE),
(2,'El mago de Oz','L.Frank Baum','EMU','donación',1,1,'L',TRUE),
(2,'Sapo y sepo, un año entero','Arnold Lobel','Alfaguara infantil','donación',1,1,'L',TRUE),
(2,'Alrededor del mundo','Monika y Dariusz Stolarczyk','Tormont','donación',1,1,'L',TRUE),
(2,'Si grande puede... ¡yo también puedo!','Beth shoshan/Petra Brown','Parragon','compra',1,1,'L',TRUE),
(2,'Mi libro de cuentos preferido','Anita Jeram','Beascoa','donación',1,1,'L',TRUE),
(2,'Mi jardín de las Hadas flores','Cicely Mary Barker','Montena','donación',1,1,'L',TRUE),
(2,'Una araña en la dulcería','Yu Yeong-So','Altea','compra',1,1,'L',TRUE),
(2,'A volar jugaba sola','Marta Romo/María Figueroa','Libros del rincón','SEP',1,1,'L',TRUE),
(2,'La zapatilla roja','Karin Grub/Tobias Krejtschi','Lóguez','compra',1,1,'L',TRUE),
(2,'Los miserables','Victor Marie Hugo','Silver dolphin','donación',1,1,'L',TRUE),
(2,'Lobos de fábula','Jesús Araújo','Parramón','donacion',1,1,'L',TRUE),
(2,'Bajo el mar','Monika y Dariusz Stolarczyk','Tormont','donacion',1,1,'I',TRUE),
(2,'Ciclo del aceite','Cristina Quental/ Mariana Magalhaes','everest','compra',1,1,NULL,TRUE),
(2,'El primer día de Camila','Yemina Mascareño','LUDOS','compra',1,1,NULL,TRUE),
(2,'¡salta! ¡cae! ¡rueda!','Michi Fujimoto','Paradise Press,Inc','donación',1,1,'L',TRUE),
(2,'Ciclo de la miel','Cristina Quental/ Mariana Magalhaes','everest','compra',1,1,'L',TRUE),
(2,'Jardín de formas','Moisés Salama','kamkio','donación',1,1,'I',TRUE),
(2,'Molly crecer es querer','Yemina Mascareño','LUDOS','compra',1,1,NULL,TRUE),
(2,'Clarita vuelve a florecer','Yemina Mascareño','LUDOS','compra',1,1,NULL,TRUE),
(2,'Lina un corazón lleno de amor','Yemina Mascareño','LUDOS','compra',1,1,NULL,TRUE),
(2,'Ricitos de oro',NULL,'Anytime Books','donación',1,1,'L',TRUE),
(2,'Los tres cochinitos',NULL,'Anytime Books','donación',1,1,'L',TRUE),
(2,'Los amigos del zoológico/Un domingo en el parque',NULL,'melbooks','donación',1,1,'L',TRUE),
(2,'Comiendo/Comprando perfumes',NULL,'melbooks','donación',1,1,'L',TRUE),
(2,'Un día muy especial/un día entrentenido',NULL,'melbooks','donación',1,1,'L',TRUE),
(2,'La pesca de papá/ el día de mamá',NULL,'melbooks','donación',1,1,'L',TRUE),
(2,'La libre y la tortuga',NULL,'García','donación',1,1,NULL,TRUE),
(2,'Cenicienta',NULL,'Sigmar','donación',1,1,NULL,TRUE),
(2,'¿Cuántos animales hay?','Brian Wildsmith','Star Bright Books','donación',1,1,'L',TRUE),
(2,'El guerrero coyote iguana','Jesús Paredes','CONAFE','SEP',1,1,'L',TRUE),
(2,'El malora del corral','Catalina Fernández  Mata','CONAFE','SEP',1,1,'L',TRUE),
(2,'El ladrón de plumas','Rodolfo Coronado','CONAFE','SEP',1,1,'L',TRUE),
(2,'Los changuitos','Arturo Ortega','CONAFE','SEP',1,1,'L',TRUE),
(4,'¿Qué hacer con la basura?','Óscar Muñoz y Rafael Robles','CONAFE','SEP',1,1,NULL,TRUE),
(4,'El mar y la costa','Luis de la Peña','CONAFE','SEP',1,1,'I',TRUE),
(4,'El quetzal','Arturo Ortega','CONAFE','SEP',1,1,'I',TRUE),
(4,'50 Aniversario CESPT','Ing.Manuel Becerra Lizardi','Impala Comucicación gráfica','donado',1,1,'I',TRUE),
(2,'El pez arcoirris y  la ballena azul','Marcus Pfister','Norte-Sur','donado',1,1,'I',TRUE),
(4,'Colonias submarinas: Arrecifes','Pedro Moreno','Exploradores Planeta','donado',1,1,'I',TRUE),
(1,'Leyendas para niños','varios','Fernández editores','compra',1,1,'L',TRUE),
(6,'Constitución para niñas y niños','Mario Herrera/Rosana González','Estado de BC','SEP',2,2,'I',TRUE),
(6,'Origami Papiroflexia',NULL,'Barco','compra',1,1,'I',TRUE),
(6,'Cómo hacer figuras geométricas y flores en papiroflexia',NULL,'Época','compra',1,1,'I',TRUE),
(1,'El Quijote de la Mancha y El Cid Campeador','Miguel de Cervantes Anónimo','Selector','compra',1,1,'L',TRUE),
(1,'El jorobado de Notre Dame y Los miserables','Victor Hugo','Selector','compra',1,1,'L',TRUE),
(1,'El periquillo Sarniento','Felipe Garrido','SEP','Donación',3,3,NULL,TRUE),
(1,'Juárez, el republicano','Josefina Zoraida Vázquez','El Colegio de México','Donación',1,1,NULL,TRUE),
(6,'Adiós a las trampas 2','Elizondo Mayer Serra','CFE','Compra',2,2,'L',TRUE),
(1,'De cómo nació la memoria de El bosque','Rocío Martínez','CFE','Compra',1,1,'L',TRUE),
(6,'¿Alguna pregunta?','Marie Louise Gay','Santillana','Compra',1,1,'L',TRUE),
(6,'El rey Arturo','Rosalind Kerven','DK','Compra',1,1,'L',TRUE),
(5,'Colección Particular','Nelson Herrera Ysla','Sótano de Rita','SEP',1,1,'L',TRUE),
(1,'Cuentos sin fronteras','Manuel del Postigio','Arhmar','Compra',1,1,'L',TRUE),
(1,'El hombre del Iztac','David Martín del Campo','Alfaguara infantil','SEP',1,1,'L',TRUE),
(1,'Cuentos africanos','Susan Akono','Labericuentos','Donación',1,1,'L',TRUE),
(1,'Los tres cerditos','John Duncan','Dalmatian Press','Donación',1,1,'L',TRUE),
(1,'Pinocho','Martha Stamps','Dalmatian Press','Donación',1,1,'L',TRUE),
(6,'Los cuates de la armadura','Pedro Moreno','Planeta Junior','Donación',1,1,'I',TRUE),
(1,'El jorobado de Notre Dame y Los miserables','Fernández Editores',NULL,'Compra',1,1,'L',TRUE),
(1,'Pocahontas','Fernández Editores',NULL,'Compra',1,1,'L',TRUE),
(1,'Mate y la Luz fantasma','Sandra Pulido','norma','Donación',1,1,'L',TRUE),
(3,'Descubre los sentidos','David Suzuki','ONIRO','donado',1,1,'I',TRUE),
(3,'Gorilas','Ian Redmond','Altea','donado',1,1,'I',TRUE),
(3,'Tortugas en peligro','Lynette evans','Santillana','donado',1,1,'I',TRUE),
(3,'El libro de los animales',NULL,'Tormont','donado',1,1,'I',TRUE),
(3,'El libro de los ambientes naturales',NULL,'Tormont','donado',1,1,'I',TRUE),
(3,'Los insectos y las arañas','Steve Roberts/Wildlife','Silver Dolphin','donado',1,1,NULL,TRUE),
(3,'La naturaleza',NULL,'Águila Real','Donado',1,1,NULL,TRUE),
(1,'Barbie el castillo de diamantes','Cliff Ruby','Mega ediciones','Donación',1,1,'L',TRUE),
(1,'Pulgarcito','Charles Perrault','Iberlibro','Compra',1,1,'L',TRUE),
(1,'Nico y los lobos feroces','Valeri Gorbachev','Norte-Sur','Compra',1,1,'L',TRUE),
(1,'Hansel y Gretel','Michael Morpurgo','Castillo','Compra',1,1,'L',TRUE),
(1,'Cars Un evento muy especial',NULL,'Greay Moments','Donación',1,1,'L',TRUE),
(1,'Las piñatas','Monique Zepeda','Alfaguara','Compra',1,1,'L',TRUE),
(1,'El flautista de Hamelin',NULL,'Grupo Editorial García','Donación',1,1,'L',TRUE),
(1,'¿ Y quién es ese señor?','Elisa Ramírez','Diseño','Compra',1,1,NULL,TRUE),
(1,'El pintor de las cosas','Gabriel López','Conafe','SEP',1,1,NULL,TRUE),
(1,'El cuervo y el Zorro',NULL,'Testa','Compra',1,1,'L',TRUE),
(1,'El traje nuevo del emperador','Colección Azahar','Editorial García','Donación',1,1,NULL,TRUE),
(1,'Las vacaciones de Franz','Christine Nöstlinger','norma','Compra',1,1,'L',TRUE),
(1,'Cuando me siento bien conmigo mismo','Cornelia Maude Spelman','Picarona','Compra',1,1,'L',TRUE),
(1,'Una aventura con Lalo Lobo','Maurice Pledger','Silver Dolphin','Compra',1,1,'L',TRUE),
(1,'Caldo de pollo para almitas','Jack Canfield','Edivision','Compra',1,1,'L',TRUE),
(1,'Pulgarcito y otros cuentos del bosque','Tiziana Merani','Montena','Compra',1,1,'L',TRUE),
(1,'Florentino, el guardador de secretos','Jorge Eslava','Alfaguara','Compra',1,1,'L',TRUE),
(1,'¿Hay  algo más grande que una ballena azul?','Robert E. Wells','Wells','Compra',1,1,NULL,TRUE),
(1,'Aurora y la corona de diamantes','Sandra Pulido','Grupo norma','Compra',1,1,'L',TRUE),
(1,'¿Cuántas Palabras?','Isaías Isabel','Al sol solito','SEP',1,1,'L',TRUE),
(1,'Emiliano Zapata','Roberto Mares','Grupo Editorial García','Compra',1,1,'L',TRUE),
(1,'Travesuritis aguda','Rafael Barajas','CFE','Compra',1,1,'L',TRUE),
(1,'Los días y los dioses del Códice Brogia','Krystyna M','Espejo de Urania','SEP',1,1,NULL,TRUE),
(6,'Historia del arte mexicano 59','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 60','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 61','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 65','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,NULL,TRUE),
(6,'Historia del arte mexicano 39','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,NULL,TRUE),
(6,'Historia del arte mexicano 66','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 68','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 42','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 22','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 28','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 29','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 54','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 55','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 56','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 57','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(6,'Historia del arte mexicano 58','SEP/INBA/SALVAT','Historia del arte mexicano','SEP',1,1,'I',TRUE),
(1,'La concha del sapo/ El gusano medidor','CONAFE','Para empezar a leer','SER',1,1,'L',TRUE),
(1,'Deshidratación','CONAFE','Cuenta conmigo','SEP',1,1,'L',TRUE),
(1,'Rimas con Pooh','Great moment PLUBLISHING','Rimas con Pooh','Donación',1,1,'L',TRUE),
(1,'Gatitos mimosos','Playmore Inc.','Playmore Inc.','Donación',1,1,NULL,TRUE),
(1,'El 35 de mayo','Erich Kastner','Alfaguara Juvenil','SEP',1,1,'L',TRUE),
(1,'Elogio del tlacuache','Roxanna Erdman','Alfaguara Infantil','SEP',1,1,'L',TRUE),
(1,'Simbad el Marino','Editores mexicanos unidos S.A','Cuentos clásicos ilustrados','Donación',1,1,'L',TRUE),
(1,'Piel de asno','Grupo editorial García S.A de C.V.','Cuentos clásicos ilustrados','SEP',1,1,'L',TRUE),
(1,'La gallina de los huevos de oro','Grupo editorial García S.A de C.V.','Cuentos clásicos ilustrados','SEP',1,1,'L',TRUE),
(1,'Los tres cerditos','Hemma ediciones','Mis mejores cuentos','Donación',1,1,'L',TRUE),
(1,'La jardinera','Ediciones Ekaré Sarah Stewart','Mis primeras lecturas','SEP',1,1,'L',TRUE),
(6,'500 Acertijos, adivinanzas, colmos y tantanes','Blanca Olivas','Libreria serie infantil','Compra',1,1,NULL,TRUE),
(1,'Peter Pan','J. M. Barrie','Nuevos cuentos clásicos','Compra',1,1,NULL,TRUE),
(1,'Hansel y Gretel','Editores mexicanos unidos S.A','Cuentos clásicos ilustrados','Compra',1,1,NULL,TRUE),
(1,'La casita de chocolate','grupo editorial García S.A de C.V.','Cuentos inolvidables','Donación',1,1,'L',TRUE),
(1,'La bella durmiente','Grupo editorial García S.A de C.V.','Colección Lorea','Compra',1,1,'L',TRUE),
(1,'La bella durmiente','grupo editorial García S.A de C.V.','Colección Lorea','Compra',1,1,'L',TRUE),
(1,'Lecturas clásias para niños','Comisión Nacional de los libros de texto',NULL,'SEP',1,1,'L',TRUE),
(1,'La lechera y el cántaro','Beatriz Barnes/ Mart Gaspar','Cuentos de Polidoro','SEP',1,1,'L',TRUE),
(1,'¡Córrele!','Marta Romo/Palomo','Primera Edición Libros del Rincón','SEP',2,2,'L',TRUE),
(6,'Veo','Walter Wick/Jean Marzollo/Carol Devine Carson','Scholastic','SEP',1,1,NULL,TRUE),
(1,'La clase de conversación','Muppets de Jim Hensen','Serie Plaza Sésamo','Compra',1,1,'L',TRUE),
(6,'Hechos y cifras de Fiji','Claire Owen','Escápate al mundo','Compra',1,1,'I',TRUE),
(6,'El libri de la Vida','Tormot','Tantas preguntas tantas respuestas','Compra',1,1,'I',TRUE),
(6,'La abundancia del mar','Pedro moreno','Exploradores aventureros','Compra',1,1,'I',TRUE),
(6,'¡Qué bueno!','Discovery channel','Sobre la tecnología más avanzada','Compra',1,1,'I',TRUE),
(6,'Introducción al arte para niños','Heather Alexander/Meredith Hamilton','Grupo editorial Tomo S.A de C.V','Compra',1,1,NULL,TRUE),
(6,'Atlas del mundo para niños','Daniela de Luca','SM saber','SEP',1,1,NULL,TRUE),
(1,'Un problema de pelos','Khoa Le','Cuentos fantásticos','Compra',1,1,'L',TRUE),
(1,'Exploradores de la naturaleza','Michi Fujimoto','¡Solo mienbros!','Compra',1,1,NULL,TRUE),
(1,'La leyenda del Sol y la Luna/La leyenda del maíz','Grupo editorial Raf','Mitos y leyendas de México','Compra',1,1,'L',TRUE),
(1,'Guía práctica del perfecto pirata','Alberto Moreno/Rodolfo Ramos','El gato de hojalata','Compra',1,1,'L',TRUE),
(1,'Las dos cabritas','Eulalia Valeri/Carme Solé Vendrell','La galera','Compra',1,1,'L',TRUE),
(1,'Dusty Fumigavión','Grupo BestWay','Aviones','Compra',1,1,'L',TRUE),
(1,'Willy el soñador','Anthony Browne','A la orilla del viendo','SEP',1,1,'L',TRUE),
(1,'Travesía Mágica','Ada Elba Pérez','Casa Editorial Abril','SEP',1,1,'L',TRUE),
(1,'La gente que nos rodea','Patricia Geis','Beascoa','Compra',1,1,'L',TRUE),
(1,'Alicia en el país de las maravillas','Hemma ediciones','Cuentecitos','Donación',1,1,'L',TRUE),
(1,'La luz azul','Andersen','Spot','Compra',1,1,'L',TRUE),
(1,'El libro de los cuentos y leyendas de Amérca Látina y España','Ilustración Jesús Gabán','Ediciones B grupo Z','Compra',1,1,NULL,TRUE),
(1,'Perdí mi sonrisa','Thierry Robberecht/Philippe Goossens','Altea','Compra',1,1,'L',TRUE),
(6,'El libro de las preguntas','Cuatro Media Inc.','Variedades','Compra',1,1,'I',TRUE),
(1,'Ratón de campo y ratón de ciudad','grupo editorial García S.A de C.V.','Los Quentos de la abuela','Compra',1,1,'L',TRUE),
(1,'Mate el grandioso','Laura Gómez Gómez','Cars Pixar','Donación',1,1,'L',TRUE),
(1,'La espada en la roca','grupo editorial García S.A de C.V.','El reino del cuento','Donación',1,1,'L',TRUE),
(1,'Un cuento para cada día','Hemma ediciones','Un cuento para cada día','Compra',1,1,'L',TRUE),
(1,'Ali Baba y los 40 ladrones','grupo editorial García S.A de C.V.','Lorea','Compra',1,1,'L',TRUE),
(1,'Destello el dinosaurio','Marcus Pfister','Scholastic Edition','SEP',1,1,'L',TRUE),
(1,'Adelaine','Tomi Ungerer','Alfaguara inantil','Donación',1,1,'L',TRUE),
(1,'Jorge el Curioso','H.A. Rey','H.M. Co.','Compra',1,1,'L',TRUE),
(1,'Sopa de niño','Loris Lesynski','Annick Press Ltd.','Compra',1,1,'L',TRUE),
(1,'Artuto y el negocio de mascotas','Marc Brown','lectorum','Compra',1,1,NULL,TRUE),
(1,'El traje nuevo del emperador','grupo editorial García S.A de C.V.','Azahar','Compra',2,2,'L',TRUE),
(3,'Del lápiz de gráfito','Fernández editores','Libros del rincón','SEP',3,3,'I',TRUE),
(1,'A camello hacia la libertad','Laurence de Arabia','Así ocurrió/Instantáneas de la historia','SEP',1,1,'L',TRUE),
(1,'Un torbellino de curiosidad','Miguel covarrubias','Así ocurrió/Instantáneas de la historia','SEP',1,1,NULL,TRUE),
(1,'Aquí vivo','Agencias de arte fotográfico','SM saber','SEP',1,1,'L',TRUE),
(1,'Del otro lado de los sueños','Eliseo Alberto','Alfaguara inantil','SEP',1,1,'L',TRUE),
(1,'La expedición de Malabí','Gabriel Saénz','Fondo de Cultura Económica','SEP',1,1,NULL,TRUE),
(1,'A Lucas todo le sale mal','María Luisa Puga','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Cuentas de elefante','Helme Heine','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Víboras vivas','Hazel Townson','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Este era un lápiz','Antonio Granados','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Las mañanitas','Ilustración Pablo Rulfo','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Donde las ballenas','Víctor Kelleher','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'El muu..sterio de la vaca descoyuntada','Belén Alonso de Santiago','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Bonícula','Deborah y James Howie','Fondo de Cultura Económica','Donación',1,1,'L',TRUE),
(1,'Del punto a la imgen','Fernández editores','Libros del rincón','SEP',2,2,'L',TRUE),
(1,'El embuste de las coles','Paul Jennings','Fondo de Cultura Económica','SEP',1,1,NULL,TRUE),
(1,'Jelou y gudbay','Tormod Haugen','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Jorge y Gloria','Tormod Haugen','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Yogo el mago','Bruno Heitz','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'El dragón de la calle','Simón Schwarz Y Samuel Finzi','Libros del rincón','SEP',1,1,'L',TRUE),
(3,'Arrecífes artificiales','Méxio desconocido','Libros del rincón','SEP',1,1,NULL,TRUE),
(1,'Detrás de la barda','Estebán Domínguez','Espejo de urania','SEP',1,1,'L',TRUE),
(1,'La pobre viejecita','Rafael Pombo/Javier Saavedra','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Hilario y la cucarcha maravillosa','Óscar Martínez Vélez','El barco de vapor','SEP',1,1,'L',TRUE),
(1,'Solicito elefante para cuento','Antonio Granados','Los piratas/El barco de vapor','SEP',1,1,'L',TRUE),
(1,'El sendero de los gatos','Sergio González Rogríguez','Travesías','SEP',1,1,NULL,TRUE),
(1,'Antología Primer grado','Antología primer grado','Antología','SEP',2,2,'L',TRUE),
(1,'Antología segundo grado','Antología segundo grado','Antología','SEP',2,2,'L',TRUE),
(1,'Antología tercer grado','Antología tercer grado','Antología','SEP',1,1,NULL,TRUE),
(1,'Los mejores cuentos de hadas del mundo','Readers Digest','Readers Digest México','Donación',1,1,'L',TRUE),
(1,'Mora: El hijo de la nueva novia de papá','Severine Vidal','Castillo','Compra',1,1,'L',TRUE),
(1,'¿Cómo se hizo este libro?','MegaScopio','SM saber','SEP',1,1,'L',TRUE),
(1,'El caballito jorobado','Libros del rincón','Libros del rincón','SEP',2,2,'L',TRUE),
(1,'La cucarachita Mondinga y el ratón Pérez','Biblioteca chapulín','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Acto seguido','Libros del rincón','Libros del rincón','SEP',1,1,'L',TRUE),
(3,'Con la casa a cuestas','Patricia Holl','MicrosCopio','SEP',1,1,'L',TRUE),
(1,'De lo que contaron al fraile','Ediciones Tecolote','Colección Ya verás','SEP',1,1,'I',TRUE),
(1,'El libro del papel','Ruth Rocha/Octavio Roth','El hombre y la comunicación','SEP',1,1,'L',TRUE),
(1,'Caperucita Roja','Adolfo Serra','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Desfile','Donald Crews','Scholastic','SEP',1,1,'L',TRUE),
(5,'Biblioteca de pequeños creadores','Niñas y niños creadores de Sonora','Consejo Nacionaf para la Cultura y las Artes','SEP',1,1,'L',TRUE),
(3,'¿Qué hacer con la basura?','Óscar Muñoz','Libros del rincón','SEP',1,1,NULL,TRUE),
(1,'El pinguino Pedro y el pequeño Timoteo','Marcus Pfister','Ediciones Norte-Sur','SEP',1,1,NULL,TRUE),
(1,'El mundo de Don Quijote','Cuentos de Plidoro','Libros del rincón','SEP',5,5,'L',TRUE),
(1,'De las hicoteas','Testimonio Recopilado','Libros del rincón','SEP',3,3,'L',TRUE),
(3,'Cazadores de rocas y fósiles','Ben Morgan','SM saber','SEP',1,1,'I',TRUE),
(3,'Mi primer diccionrio de fauna de México','Pedro moreno','SM saber','SEP',1,1,'I',TRUE),
(1,'Quiero a mi papá porque...','Laurel Porter-Gaylord','Dutton','Donación',1,1,'L',TRUE),
(1,'Las mañanitas','Pablo Rulfo','Libros del rincón','SEP',1,1,NULL,TRUE),
(1,'Pipis y gañas','José Antonio Hernández Amzcua','Libros del rincón','SEP',2,2,'L',TRUE),
(1,'La Legión de la Tarántula','Pedro Bayona','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Teseo y el monotauro','Cuentos de Plidoro','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'El payaso que no hacía reír','Enrique Martínez y Enrique Pérez','Libros del rincón','SEP',1,1,NULL,TRUE),
(1,'A volar jugaba sola','Marta Romo/María Figueros','Libros del rincón','SEP',1,1,'L',TRUE),
(3,'Cuadrados mágicos y otras cosas','Claire Owen','Divulgaición Santillana','Compra',1,1,'I',TRUE),
(1,'Sal Solecito','McMillan','CuentaMundos','Donación',1,1,NULL,TRUE),
(3,'Tesoros Ocultos','Mas-Ivars Editores/Francois Cherrier','Tesoros','SEP',1,1,NULL,TRUE),
(1,'María y los vientos','Jesús Paredes','Consejo Nacionaf para la Cultura y las Artes','SEP',1,1,'L',TRUE),
(3,'El huerto tradicional','CONAFE','Educación ambiental','SEP',1,1,'I',TRUE),
(3,'El cuento de la violencia','Santigo Genovés','Libros del rincón','SEP',1,1,'L',TRUE),
(3,'Temas de educación sexual, equidad de género y prevención de adicciones',NULL,'Sexto grado','SEP',1,1,'I',TRUE),
(1,'Soy Huichol','Refugio González','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Los piratas','Francisco Fernández','Libros del rincón','SEP',1,1,'L',TRUE),
(5,'Acto seguido','Gerardo Cirianni/Gloria Elena Bernal','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'María la curandera','Monique Zepeda','Libros del rincón','SEP',1,1,'L',TRUE),
(1,'Queta la vaca coqueta','Martha Sastrías','Fondo de Cultura Económica','Compra',1,1,'L',TRUE),
(5,'¿Jugamos al teatro?','Berta Hiriart','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(3,'Huerta: Cosecha lo que siembras','Mónica Martin','Nuevo modelo educativo','SEP',1,1,NULL,TRUE),
(12,'Juegos para fiestas','El mago arlequín','Selector','Compra',1,1,'I',TRUE),
(13,'Cositas para hacer','Laurie Carlson','Selector','Compra',1,1,'I',TRUE),
(1,'Antología sexto grado','Antología sexto grado','Antología','SEP',2,2,'L',TRUE),
(5,'Las mejores poesías para niños','Selección','Nuevo talento','Donación',1,1,'L',TRUE),
(1,'Cuentos pra compartir','Eduardo Villegas','Selector','Compra',1,1,'L',TRUE),
(1,'Moby Dick','Hermn Melville','Selector','Donación',1,1,'L',TRUE),
(1,'Mitología Mexicana para niños','Gabriela Santana','Selector','Donación',1,1,'L',TRUE),
(13,'Huellas y rayitas','Blanca Cecilia Macedo/Miguel Martínez Sarmiento','Selector','Donación',1,1,NULL,TRUE),
(6,'José María Morelos y Pavón','Alfredo Hernández Murillo','Símbolos, forjadores de la Patria','Donación',1,1,'I',TRUE),
(1,'Antología quinto grado','Antología quinto grado','Antología quinto grado','SEP',2,2,'L',TRUE),
(1,'Examen de miedo','Yolanda Reyes','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'El libro de oro de los niños','Verónica Uribe','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Luciano el gusano','Santiago González','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Los huevos','Philippe Simon','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Al otro lado del jardín','Jairo Buitrago','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'El oficial Correa y Gloria','Peggy Rathmann','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(12,'Juego tradicionales','María Angélica Ovalle','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Nungún lugar adonde ir','Marie Francine Hebert/Janice Hadeau','SM saber','SEP',1,1,'L',TRUE),
(6,'Derechos humanos','INEA','Educación pra la vida','SEP',1,1,'I',TRUE),
(6,'Trabajo y empleo','INEA','Educacion para la vida','SEP',1,1,'I',TRUE),
(1,'Navegando por el arcoiris','Talleres de creación literaria','Sistema educativo estatal','SEP',2,2,'L',TRUE),
(1,'Puros cuentos','Concurso autores tijuanenses','Sistema educativo estatal','SEP',2,2,'L',TRUE),
(1,'Los niños cuentan','Cuentos infantiles niños tijuanenses','SIstema educativo estatal','SEP',1,1,'L',TRUE),
(1,'El paquete parlante','Gerard Durrel','Biblioteca juvenil','SEP',1,1,'L',TRUE),
(1,'Una historia familiar','Christine Nostlinger','Biblioteca juvenil','SEP',1,1,'L',TRUE),
(1,'Grethen se preocupa','Christine Nostlinger','Biblioteca juvenil','SEP',1,1,'L',TRUE),
(1,'Una mascota inesperada','Karen Chacek','Castillo','Compra',1,1,'L',TRUE),
(5,'Poesías, recitales y fábulas para niños','Editores mexicanos','Editores Mexiacanos Unidos S.A','Compra',2,2,'L',TRUE),
(5,'Canciones y poemas par niños','Federico García Lorca','Labor bolsillo juvenil','Compra',1,1,'L',TRUE),
(1,'Maroma y la mariposa roja','Ana María Machado','Castillo','Compra',1,1,'L',TRUE),
(1,'Cuentos sin fronteras','Manuel del postigo','Narrativa de autores mexicanos','Compra',1,1,'L',TRUE),
(1,'Juanito Fuelle','Jesús Ballaz','Autral juvenil','compra',1,1,'L',TRUE),
(1,'La brujita telaraña','Alejandro Negrín','Pocas letras','SEP',1,1,'L',TRUE),
(11,'Acercándose y acercándose','Rebel Williams','TWG Books','Donación',1,1,'L',TRUE),
(1,'Gata va al río','Graciela Vidal','Schoolastic','Compra',1,1,NULL,TRUE),
(11,'El tigrillo','Rose Mary Berlín','Libros de l selva','Donación',1,1,'L',TRUE),
(1,'El signo del buey','Megan Stine','Grupo editorial Norma','Donación',1,1,NULL,TRUE),
(1,'Cinco formas para deshacerme de mi hermano','Tamar Cohen','CASTIllo','Compra',1,1,'L',TRUE),
(1,'El silencio de Orlando','Homero Aridjis','Cuentos de nuestra América','Compra',1,1,'L',TRUE),
(11,'Acordeón: La costa, el bosque, el desierto, la ciudad, la selva (Colección)','Mayela Crisóstomo','Mi comunidad','Compra',1,1,'L',TRUE),
(1,'Amelia Bedelia','Peggy Parish','Lectorum','Donación',1,1,'L',TRUE),
(1,'Cómo abrió don Nicanor el Gran Circo Volador','Mar Benegas/Ximo Abadía','Nuevo modelo educativo','SEP',1,1,'L',TRUE),
(1,'Puros cuentos 2','Concurso autores tijuanenses','SIstema educativo estatal','SEP',4,4,NULL,TRUE),
(2,'La bella durmiente','Disney','Disney','Donación',1,1,NULL,TRUE),
(1,'La reina de las nieves','Grupo editorial García','Azahar','Donación',1,1,'L',TRUE),
(1,'María Celeste','Carmen Posadas','Fondo de Cultura Económica','SEP',1,1,'L',TRUE),
(1,'Hurra por nuestros héroes','Sesame Street','Sesame Street','Donación',1,1,'L',TRUE),
(1,'Las chivas locas/El maíz y la arrierita','Mario Aburto/Rubén Fisher','CONAFE','SEP',1,1,'L',TRUE),
(1,'El soldadito de plomo','Colección infantil','Colección infantil','Donación',1,1,'L',TRUE),
(1,'Maya y el truco para hacer la tarea','Jo Pestum','Fondo de Cultura Económica','compra',1,1,'L',TRUE),
(1,'El embuste de las coles','Paul Jennings','Fondo de Cultura Económica','compra',1,1,'L',TRUE),
(3,'Plantas medicinales','Bertha Zelayrán','Plantas y yerbas medicinales','Donación',1,1,NULL,TRUE),
(1,'La desaparición de la abuela','Isabel Álvarez de la Peza','El barco de vapor','Compra',1,1,'L',TRUE),
(1,'Una zarigueya en mi mochila','Érika Marcela Zepeda Montañez','El barco de vapor','compra',1,1,'L',TRUE),
(1,'Cuentos y poesías para los jóvenes','Compilación','Libro de cuentos y poesía','Donación',1,1,'L',TRUE),
(8,'Mis derechos mis colores','ILCSA Ediciones','IMAC','Donación',1,1,'I',TRUE),
(1,'Ana, ¿Verdad?','Francisco Hinojosa','Alfaguara inantil','Compra',1,1,NULL,TRUE),
(1,'El oso que no lo era','Frank Tashlin','Alfaguara inantil','Compra',1,1,'L',TRUE),
(5,'Del pellejo de una pulga y otros versos para jugar','Manuel Peña Muñoz','Alfaguara inantil','Compra',1,1,'L',TRUE),
(9,'¿Quién fue Albert Einstein?','Jess Brallier','Altea','Compra',1,1,NULL,TRUE),
(1,'Sinfonía Natural','Leticia Herrera Álvarez','Alfaguara inantil','Compra',1,1,'L',TRUE),
(1,'El nido de la Cigueña','Fidel González Zurita','Alfaguara inantil','Compra',1,1,'L',TRUE),
(3,'Jardines flotantes Xochimilco','Pedro  Moreno','Pequeños exploradores','Donación',1,1,'I',TRUE),
(1,'Una sonrisa llamada Luís','Ziraldo','Melbooks','Donación',1,1,'L',TRUE),
(3,'Para los amantes de la naturaleza','W. Lockwood','Letras','Compra',1,1,NULL,TRUE),
(1,'El torito','Reyes S. Tamez Guerra','Pocas letras','Compra',1,1,'L',TRUE),
(1,'El baile de los manatíes','Faith McNulty','Scholastic','Compra',1,1,'L',TRUE),
(1,'El libro de la selva','Disney','Great Moments','Compra',1,1,'L',TRUE),
(1,'Gato pinto','Miguel Limón','Pocas letras','Compra',1,1,'L',TRUE),
(1,'Muchacho Azul','Miguel Limón','Pocas letras','Compra',1,1,'L',TRUE),
(1,'Loros en emergencia','Emilio Carballido','Fondo de Cultura Económica','Compra',1,1,'L',TRUE),
(11,'Fito el mapache','Dirección de medios','CONAFE','SEP',1,1,'L',TRUE),
(11,'Susy y Arquímedes','Eva Furnari','Punto de escuentro','Compra',4,4,'L',TRUE),
(1,'El elefante y la rana','Peter Ruterford','Juega a leer','Compra',1,1,'L',TRUE),
(1,'La gran limpieza de Víctor el castor','Hemma','Aprendo a leer con...','Compra',1,1,'L',TRUE),
(1,'Ricitos de oro y los tres osos','Dalmatian Press','Dalmatian Press','Compra',1,1,'L',TRUE),
(1,'El extraordinario Félix Feliz','Jordi Sierra I Fabra','Cuentos de nuestra América','Compra',1,1,'L',TRUE),
(1,'Carta abierta a las niñs y los niños','Rosa María Torres','Libros del rincón','SEP',1,1,'L',TRUE),
(3,'Medio ambiente','Gloria Araceli Borja/Luis Sánchez','Educación para la vida','SEP',1,1,'I',TRUE),
(3,'Participación Social','Gloria Araceli Borja','Educación para la vida','SEP',1,1,'I',TRUE),
(1,'El aguacate','Rosalía Chavelas','Frutos prodigiosos','Compra',1,1,'L',TRUE),
(3,'Cómo funcionan las cosas','Sophie Dauvois','Nuevo modelo educativo','SEP',1,1,NULL,TRUE),
(3,'Mi primer libro de plantas caurtivas y tóxicas','Salatiel Barragán','SM saber','Compra',1,1,'I',TRUE),
(1,'Esto no es','Alejandro Magallanes','SM saber','Compra',1,1,'L',TRUE),
(14,'Marvel','Editorial Marvel','Marvel','Donación',5,5,NULL,TRUE),
(1,'The lost dinosaur bone','Mercer Mayer','Little Critter','Donación',1,1,'I',TRUE),
(1,'Tron Legacy','Disney','Disney','Donación',1,1,'L',TRUE),
(1,'Marvel súper héroes','Editorial Marvel','Marvel','Donación',1,1,NULL,TRUE),
(1,'El señor de los anillos: La comunidad del anillo 1','Jrr Tolkien','Minotauro','Donación',1,1,'L',TRUE),
(9,'Gandhi','Josefina Torres','Líderes espirituales','Donación',1,1,'L',TRUE),
(10,'Juárez el republicano','Josefina Zoraida Vázquez','El colegio México','SEP',2,2,'L',TRUE),
(10,'Introcucción histórica a la Revolución mexicana','Javier Garciadiego','El colegio México','SEP',2,2,NULL,TRUE),
(2,'El periquillo sarniento','José Joaquín Fernández de Lizardi','Felipe Garrido','SEP',2,2,NULL,TRUE),
(10,'Sor Juana Inés de la Cruz','Marcela Altamirano','Los grandes mexicanos','SEP',1,1,'L',TRUE),
(10,'Quetzalcótl','Luis Rutiaga','Los grandes mexicanos','SEP',1,1,'L',TRUE),
(10,'José María Morelos','Rafaela Rutiaga','Los grandes mexicanos','SEP',1,1,'L',TRUE),
(10,'Netzahualcóyotl','Luis Rutiaga','Los grandes mexicanos','SEP',2,2,'L',TRUE),
(1,'Leyendas prehispánicas mexicanas','Otilia Meza','Panorama','Compra',1,1,'L',TRUE),
(15,'Español Tercer Grado','SEP','SEP','SEP',1,1,'L',TRUE),
(1,'Habría que...','Thierry Lenain','SM saber','SEP',1,1,NULL,TRUE),
(1,'La hora de los cuentos','Tormont','Tormont','Donación',1,1,'L',TRUE),
(1,'Leony','Yemina Mascareño','Ludos','Donación',1,1,'L',TRUE),
(3,'El libro de los dinosaurios','Pilar Obón','Época','Donación',1,1,NULL,TRUE),
(3,'The megbook of 3d thrillers','Arcturus','Arcturus','Donación',1,1,'I',TRUE),
(3,'Meet the dinosaurs','Readers','Readers','Donación',1,1,NULL,TRUE),
(1,'Jasmín y la estrella persa','Lara Bergen','Grupo Editoril Norma','Donación',1,1,'L',TRUE),
(6,'Encilopedia ilustrada','Disney','Disney','Compra',1,1,NULL,TRUE),
(6,'El cuerpo humano','Enciclopedia Británica','Hechos Fascinantes','Compra',1,1,NULL,TRUE),
(1,'Castillo del Terror','Lourdes Urrea','CASTIllo','Compra',1,1,NULL,TRUE),
(6,'Mi Tijuana','Jhoana Mora','Santillana','Donación',2,2,'I',TRUE),
(1,'El viaje al revés','Marie-Danielle Croteau','sm','Compra',1,1,'L',TRUE),
(1,'Harry Potter y el prisionero de Azkaban','J.K Rowling','salamandra','Compra',1,1,'L',TRUE),
(1,'¿A qué huelen las guayabas?','Eva Salgado','SEP','Donación',1,1,NULL,TRUE),
(1,'Cuentos de Dragones para niños','Luis Rutiaga','RM ediciones','Compra',1,1,'L',TRUE),
(2,'El diluvio','Rodolfo Fonseca','Pocas letras','Donación',1,1,'L',TRUE),
(2,'El primer dia de Camila','Yemina Mascareño','LUDOS','Donación',1,1,'L',TRUE),
(2,'Ricardo','Helme Heine','Fondo de Cultura Económica','Donación',1,1,'L',TRUE),
(2,'Two by Two','Franklin','Dalmatian Press','Compra',1,1,'L',TRUE),
(2,'El que no hacía reír','Enrique Martínez y Enrique Pérez','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'La vaca que decía Oink','Bernarda Most','Lector un','Donación',1,1,'L',TRUE),
(2,'Exploradores de la naturaleza','Michi Fujimoto','Solo miembros','Donación',1,1,'L',TRUE),
(2,'Felices en la granja','Ami Houston','Dálmatan press','Donación',1,1,'L',TRUE),
(2,'La lechera','Mabel Pierola','Scholastic','Donación',1,1,'L',TRUE),
(2,'Itsy Bitsy Spiderman','Janell Cannon','Lanzar','Donación',1,1,'L',TRUE),
(2,'Stelaluna','Janell Cannon','Editorial juventud','Donación',1,1,'L',TRUE),
(2,'El cofre del tesoro','Dominique Falda','Higher in canada','Donación',1,1,'L',TRUE),
(2,'?Es oscura ? ?Es clara?','Mary Lankford','Scholastic','Donación',2,2,'L',TRUE),
(2,'La hiliada','Homero','Libros del rincón','Donación',1,1,'L',TRUE),
(6,'Introducción hostorica ala revolución mexicana','Javier García Diego','El colegio de méxico','Donación',2,2,'L',TRUE),
(6,'Puros cuentos','Roberto Castillo','Secundarias tijuana','Donación',1,1,'L',TRUE),
(6,'Charles Darwin','Dennis Hamlet','Libros del rincón','Donación',1,1,'L',TRUE),
(6,'Las brujas','Roald Dahl','Alfaguara infantil','Donación',1,1,'L',TRUE),
(6,'Cuentos elegidos','Jack London','Libros del rincón','Donación',1,1,'L',TRUE),
(6,'Suspenso en la bahía','Susan Sharpe','Fondo de cultura económica','Donación',1,1,'L',TRUE),
(6,'La séptima expedición al malabi','Gabriel Sáez','Fondo de cultura economíca','Donación',1,1,'L',TRUE),
(6,'El libro salvaje','Juan Villoro','SEP','Donación',1,1,'L',TRUE),
(4,'?Que hay en el mar?','Lada Josefa Kratky','Macmillan','Donación',1,1,'I',TRUE),
(2,'Butterfly Mariposa','Susan Cañizares','Scholastic inc','Donación',1,1,'I',TRUE),
(2,'Trenes','Gail Gibbons','Scholastic inc','Donación',1,1,'I',TRUE),
(2,'?Goma de mascar o chicle?','Pedro moreno','Exploradores del planeta','Donación',1,1,'I',TRUE),
(2,'La orilla del mar','Pedro moreno','Exploradores del planeta','Donación',1,1,'I',TRUE),
(2,'En marcha','Ann Morris','Scholastic','Donación',1,1,'I',TRUE),
(2,'El cultivo de la calabaza','Marcio Lopez','Libros del rincon','Donación',1,1,'L',TRUE),
(2,'De sol a sol','Gail Gibbons','Scholastic','Donación',1,1,'L',TRUE),
(2,'El mercado','Leticia Méndez','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'El royo mocho','Carmen Berenguer','Ediciones Ekare','Donación',1,1,'L',TRUE),
(2,'El agua siempre cambia','Lisa Westberg Peters','Scholastic','Donación',1,1,'L',TRUE),
(2,'La peor señora del mundo','Francisco Hinojosa','Fondo de cultura económica','Donación',1,1,'L',TRUE),
(2,'Duerme mi sueño !','Antton Kazabon','Ediciones mensajero','Donación',1,1,'L',TRUE),
(2,'Frida','Jonáh Winter','Ediciones mensajero','Donación',1,1,'L',TRUE),
(2,'Capullo rojo','Kobo Abe','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'Blanca Nieves y los 7 enanos',NULL,'Grupo editorial García','Donación',1,1,'L',TRUE),
(2,'Las manzanas del SR. Peabody','Madona','Scholastic','Donación',1,1,'L',TRUE),
(2,'La ovejita negra','Elizabeth Shaw','FCE','Donación',1,1,'L',TRUE),
(2,'El cuento de los contadores de cuentos','Claudio Romo','FCE','Donación',1,1,'L',TRUE),
(2,'Aladino y la lámpara maravillosa','Anónimo','Cuentos infantiles','Donación',1,1,'L',TRUE),
(2,'Orfeo','Antonio Javier Caparo','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'El mundo fantástico de las fábulas',NULL,'Mis lectores','Donación',1,1,'L',TRUE),
(2,'La liebre y la tortuga',NULL,'Grupo editorial García','Donación',1,1,'L',TRUE),
(2,'La niña del mar','Jesús Paredes','Pocas letras','Donación',1,1,'L',TRUE),
(2,'Un dinosaurio en peligro','Sharon Gordon','Troll associates','Donación',1,1,'L',TRUE),
(2,'David el poeta 8','Flora Fiacre','Pomaire','Donación',1,1,'L',TRUE),
(2,'Hora de aventura','Cartoon network','Kamito','Donación',1,1,'L',TRUE),
(2,'Hoy soy una apache','Patricia Geis','Beascoa','Donación',1,1,'L',TRUE),
(2,'El nombre de las brujas','Guadalupe Alemán Lascurain','Alfaguara infantil','Donación',1,1,'L',TRUE),
(2,'Mascotas fantásticas','Carmen Campuzano','Colección infantil','Donación',1,1,'L',TRUE),
(2,'El sombrero mágico','Rosario Ferre','Alfaguara','Donación',1,1,'L',TRUE),
(2,'Arturo y el negocio de mascotas','Marc Brown','Lectorum','Donación',1,1,'L',TRUE),
(2,'Cuentos de abuela coneja','Guadalupe espejo','Alfaguara infantil','Donación',1,1,'L',TRUE),
(2,'La fiesta','Leticia Herrera','Alfaguara','Donación',1,1,'L',TRUE),
(2,'Los mejores amigos','Rachel  anderson','Alfaguara','Donación',1,1,'L',TRUE),
(2,'La casa del caracol','Luz María Chápela','Alfaguara','Donación',1,1,'L',TRUE),
(2,'El patito feo',NULL,'Editorial García','Donación',1,1,'L',TRUE),
(2,'Emil','Tomi Ungerer','Alfaguara infantil','Donación',1,1,'L',TRUE),
(2,'Alexander y el día terrible, horrible, espantoso, horroroso','Judith Viorst','Scholastic','Donación',1,1,'L',TRUE),
(2,'La culebra de la ratonera','Miguel Limon Rojas','Conafe','Donación',1,1,'L',TRUE),
(2,'Bambi',NULL,'Grupo editorial García','Donación',1,1,'L',TRUE),
(2,'El medio pollito','Rosario Ferre','Alfaguara','Donación',1,1,'L',TRUE),
(2,'Cuentos de los abuelos','Rubén Bonifaz Nuño','Conaculta','Donación',1,1,'L',TRUE),
(2,'Jackie Chan','Megan Stine','Grupo editorial norma','Donación',1,1,'L',TRUE),
(2,'Pinocho','Carlo Callodi','Nuevo talento','Donación',1,1,'L',TRUE),
(2,'Caroline Zucker','Jan Bradford','A troll book','Donación',1,1,'L',TRUE),
(2,'Los sueños y pesadillas de Toñito','Guadalupe Rivemar','Con vivatijuana','Donación',1,1,'L',TRUE),
(2,'A pero irá roja tal como se lo contaron a Jorge','Luis Maria Pescetti','Alfaguara','Donación',1,1,'L',TRUE),
(2,'Como logró el leopardo las manchas en la piel','Rudyard Kipling','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'El pirata de la pata de palo','Triunfo Arciniegas','Editorial panamericana','Donación',1,1,'L',TRUE),
(2,'Todos los osos son zurdos','Ignacio Padilla','Fondo de cultura económica','Donación',1,1,'L',TRUE),
(5,'La boda de la rayita y más teatro cuentos','Mireya Cueto','Libros del rincón','Donación',1,1,'L',TRUE),
(5,'Tortuguita se perdió','Margarita Londoño','Torre de papel','Donación',1,1,'L',TRUE),
(6,'La chistera maravillosa','Cristina pacheco','Astrolabio','Donación',1,1,'L',TRUE),
(6,'A golpe de calcetín','Francisco Hinojosa','Fondo de cultura económica','Donación',1,1,'L',TRUE),
(6,'Kostia','Arcadio Averchenko','Libros del rincón','Donación',1,1,'L',TRUE),
(6,'Amigos del alma','Elvira Lindo','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'Del tamaño justo','Ana María Machado','Astrolabio','Donación',1,1,'L',TRUE),
(2,'La tinta de las moras','Georgina Hernández Samaniego','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'La tortuga gigante','Horacio Quiroga','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'Leyendas de Becquer contadas a los niños','Rosa Navarro Duran','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'Hatching Magic','Ann downer','Libros del rincon','Donación',1,1,'L',TRUE),
(2,'Asquerosidades','Silvia Branzei','Libros del rincón','Donación',1,1,'I',TRUE),
(2,'El abuelo ya no duerme en el closet','Silvia Molina','Libros del rincón','Donación',1,1,'L',TRUE),
(2,'El enmascarado de lata','Vivían Mansour','Fondo de cultura económica','Donación',1,1,'L',TRUE),
(2,'Historia medio al revés','Ana María Machado','Fondo de cultura económica','Donación',1,1,'L',TRUE),
(1,'Los primeros automoviles','Eugene Rachlis','NOVARO','Donación',1,1,'I',TRUE),
(2,'El pollo que no quiso ser gallo','Marco Tulio Aguilera Garramuño','Loqueleo','Donación',1,1,'L',TRUE),
(2,'Mi mascota es una bacteria','Rafael Barajas','Loqueleo','Donación',1,1,'I',TRUE),
(2,'La Jirafa, el pelícano y el mono','Roald Dahl','Loqueleo','Donación',1,1,'L',TRUE),
(2,'¿Seguiremos siendo amigos?','Paula Danziger','Loqueleo','Donación',1,1,'L',TRUE),
(2,'Hotel monstruo Bienvenidos','Verónica Murguía','Loqueleo','Donación',1,1,'L',TRUE),
(7,'Mi primer Diccionario Ilustrado','Elsa Garza','Editorial García','Donación',1,1,NULL,TRUE),
(2,'A sumer of riding','Susan Hughes','Maison Battat INC.','Donación',1,1,NULL,TRUE),
(2,'El Diario de Ana Frank','Daniel Rops','Editorial Época, S.A. de C.V.','Donación',1,1,NULL,TRUE),
(2,'Donde las ballenas cantan','Victor Kelleher','Fondo de Cultura Económica','Donación',1,1,NULL,TRUE),
(2,'18 Historias de Princesas y de Hadas','Élodie Agin','Editorial Pirueta','Donación',1,1,NULL,TRUE),
(2,'Ana, la menonita migrante','Maxine Trottier','Libros de Alba','Donación',1,1,NULL,TRUE),
(2,'Al señor Lobo le duele la muela','Alain Boyer','Ediciones Mega','Donación',1,1,NULL,TRUE),
(2,'¡Mi tía es verde!','Xosé Cermeño','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Los compás y el Diamantito legendario','Mikecrack, El trollino, Timba VK','Editorial Planeta','Donación',1,1,NULL,TRUE),
(2,'Bram Stoker: Un Vampiro Romántico','Laura Navarro','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Francisco Sarabia: Conquistador del Cielo','José Montelongo','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Los fantasmas de Pico de Cuervos','Hugh Scott','Fondo de cultura económica','Donación',1,1,NULL,TRUE),
(2,'Bajo el espino','Martina Conlon-McKenna','Fondo de cultura económica','Donación',1,1,NULL,TRUE),
(2,'El monstruo de la lluvia','Marilar Aleixandre','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Donde nadie oye mi voz','Juan Carlos Quezadas','Norma','Donación',1,1,NULL,TRUE),
(2,'Mambrú perdió la guerra','Irene Vasco','Fondo de cultura económica','Donación',1,1,NULL,TRUE),
(2,'La niña del vestido antiguo y otras historias pavorosas','Alfonso Orejel Soria','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'El extraño caso de Santi y Ago','Paulina del Collado','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Los días de Lía','Edmée Pardo','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Los cuatro amigos de siempre','Gilberto Rendón Ortiz','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Tatiana y el misterio del Keon en el campamento','Francisco Hinojosa','Norma','Donación',1,1,NULL,TRUE),
(2,'La familia Guácatela','Mauricio Paredes','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'Danny, el campeón del mundo','Roald Dahl','Editorial Santillana','Donación',1,1,NULL,TRUE),
(2,'La desaparición de la abuela','Isabel Álvarez de la Peña','Ediciones SM','Donación',1,1,NULL,TRUE),
(2,'El horrible sueño de Harriet y otros cuentos de terror','Anthony Horowitz','Fondo de cultura económica','Donación',1,1,NULL,TRUE),
(2,'Llamadas de Ámsterdam','Juan Villoro','Almadia Ediciones','Donación',1,1,NULL,TRUE),
(2,'El viaje a la nada','Alfredo Ruiz Islas','Norma','Donación',1,1,NULL,TRUE),
(2,'Duérmete ya, Teresita','Javier Arévalo','Norma','Donación',1,1,NULL,TRUE),
(2,'Gravity Falls: Dimension Desconocida','Rob Renzetti','Disney Enterprises, Inc.','Donación',1,1,NULL,TRUE),
(2,'Gravity Falls: Guía de Misterio y Diversión','Disney','Disney Enterprises, Inc.','Donación',1,1,NULL,TRUE),
(2,'Las mil y una noches para niños',NULL,'Editorial Época','Donación',1,1,NULL,TRUE),
(2,'El tesoro del Cementerio','Roberto Pavanello','Monte a','Donación',1,1,NULL,TRUE),
(2,'Hilario y la cucaracha maravillosa','Oscar Martínez Vélez','Ediciones sm','Donación',1,1,NULL,TRUE),
(2,'Lo que sí y lo que no','Verónica Murguía','Libros del rincón','Donación',1,1,NULL,TRUE),
(2,'Mi mamá','Anthony Browne','Fondo de cultura económica','Donación',1,1,NULL,TRUE),
(2,'Marina, marina, ¿dónde estás?','David Plaut','Libros del rincón','Donación',1,1,NULL,TRUE),
(2,'El libro de Trucos de Magia del Aprendiz de Brujo','Janice Eaton Kilby y Terry Taylor','Libros del rincón','Donación',1,1,NULL,TRUE),
(2,'Miremos dentro del T. Rex','Dennis Schatz','Novelty Ediciones','Donación',1,1,NULL,TRUE);

